esphome:
  name: ac_zhjt03
  friendly_name: AC ZHJT03

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
captive_portal:

# --- IR ---
remote_receiver:
  pin:
    number: GPIO27
    inverted: true
  dump: raw
  tolerance: 35%
  idle: 25ms

remote_transmitter:
  pin: GPIO33
  carrier_duty_percent: 50%

# --- Temp sensor (for HA current_temperature) ---
sensor:
  - platform: dht
    pin: GPIO26
    model: DHT11
    temperature:
      name: "Temperature"
      id: t_amb
    humidity:
      name: "Humidity"
    update_interval: 30s

# --- Nuestro climate externo ---
external_components:
  - source:
      type: local
      path: custom_components

climate:
  - platform: zhjt03_climate
    name: "ZH/JT-03 AC"
    transmitter_id: ir_tx
    ambient_temperature_sensor: t_amb

    min_temperature: 16
    max_temperature: 31
    temperature_step: 1

    # defaults al boot (ajusta a gusto)
    default_mode: COOL
    default_fan_mode: AUTO
    default_temperature: 25

    # si quieres partir sin swing
    default_swing: "OFF"

# id del transmitter (para que el componente lo use)
globals:
  - id: ir_tx
    type: esphome::remote_transmitter::RemoteTransmitterComponent*
    restore_value: no
    initial_value: 'nullptr'

